# Header
menu:
  首頁: /
  關於我們: /about
  搜尋: /search
  程式設計教學: /tutorials
  社群連結:
    url: https://portaly.cc/happycoder
  FB 交流社群:
    url: https://www.facebook.com/groups/HappyCoderOrg
  訂閱 RSS: /atom.xml
  臉書粉絲頁:
    url: https://www.facebook.com/HappyCoderOrg
    icon: facebook
  Instagram:
    url: https://www.instagram.com/happycoder_org
    icon: instagram
  Youtube:
    url: https://www.youtube.com/@HappyCoderOrg
    icon: youtube
  Github:
    url: https://github.com/HappyCoderOrg
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 

# URL of the Home page image
index_cover: /img/banner-s.jpg
url: https://www.happycoder.org

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: happycoderorg
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-91250039-1

# Addthis ID
addthis: ra-5891d7d0431b8118

# set your own favicon
favicon: /img/favicon.png

# Social Accounts
twitter_url:
twitter_handle:
facebook_url: https://www.facebook.com/HappyCoderOrg
instagram_url: https://www.instagram.com/happycoder_org
youtube_url: https://www.youtube.com/@HappyCoderOrg
github_url: https://github.com/HappyCoderOrg
gitlab_url:
linkedin_url:
mailto: happycoderorg@gmail.com